name: Docker Build

'on':
    push:
        tags: [ '*.*.*-*' ]
        branches: [ main ]
    pull_request:
        branches: [ main ]

env:
    DOCKER_IMAGE: etriasnl/varnish

jobs:
    build:
        strategy:
            matrix:
                runner: [ ubuntu-latest, ubuntu-bizhost ]
        runs-on: ${{ matrix.runner }}
        steps:
            -
                uses: actions/checkout@v4.2.2
            -
                uses: docker/setup-buildx-action@v3.8.0
            -
                id: build
                uses: docker/build-push-action@v6.10.0
                with:
                    context: .
                    load: true
                    # https://docs.docker.com/build/ci/github-actions/cache/#github-cache
                    cache-from: type=gha
                    cache-to: type=gha,mode=max
            -
                run: |
                    docker run --rm --entrypoint=sh "${{ steps.build.outputs.imageid }}"
    push:
        needs: [ build ]
        runs-on: ubuntu-bizhost
        if: github.ref_type == 'tag'
        steps:
            -
                uses: actions/checkout@v4.2.2
            -
                uses: docker/setup-buildx-action@v3.8.0
            -
                uses: docker/login-action@v3.3.0
                with:
                    username: ${{ secrets.DOCKER_HUB_USERNAME }}
                    password: ${{ secrets.DOCKER_HUB_PASSWORD }}
            -
                id: meta
                uses: docker/metadata-action@v5.6.1
                with:
                    images: ${{ env.DOCKER_IMAGE }}
            -
                uses: docker/build-push-action@v6.10.0
                with:
                    context: .
                    push: true
                    platforms: linux/amd64,linux/arm64
                    tags: ${{ steps.meta.outputs.tags }}
                    labels: ${{ steps.meta.outputs.labels }}
