name: Docker Build

'on':
    push:
        tags: [ '*.*.*-*' ]
        branches: [ main ]
    pull_request:
        branches: [ main ]

env:
    DOCKER_IMAGE: etriasnl/varnish

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -
                uses: actions/checkout@v3.6.0
            -
                uses: docker/setup-buildx-action@v2.10.0
            -
                id: build
                uses: docker/build-push-action@v4
                with:
                    context: .
                    load: true
                    # https://docs.docker.com/build/ci/github-actions/cache/#github-cache
                    cache-from: type=gha
                    cache-to: type=gha,mode=max
            -
                run: |
                    docker run --rm --entrypoint=sh "${{ steps.build.outputs.imageid }}"
            -
                uses: docker/login-action@v2.2.0
                with:
                    username: ${{ secrets.DOCKER_HUB_USERNAME }}
                    password: ${{ secrets.DOCKER_HUB_PASSWORD }}
                if: github.ref_type == 'tag'
            -
                id: meta
                uses: docker/metadata-action@v4.6.0
                with:
                    images: ${{ env.DOCKER_IMAGE }}
                if: github.ref_type == 'tag'
            -
                uses: docker/build-push-action@v4
                with:
                    context: .
                    push: true
                    tags: ${{ steps.meta.outputs.tags }}
                    labels: ${{ steps.meta.outputs.labels }}
                if: github.ref_type == 'tag'
