name: Publish

'on':
    workflow_dispatch:
    push:
        tags:
            - '*.*.*-*'

env:
    DOCKER_IMAGE: etriasnl/varnish

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            -
                uses: actions/checkout@v3.5.3
            -
                uses: docker/setup-buildx-action@v2.6.0
            -
                uses: docker/login-action@v2.2.0
                with:
                    username: ${{ secrets.DOCKER_HUB_USERNAME }}
                    password: ${{ secrets.DOCKER_HUB_PASSWORD }}
            -
                id: meta
                uses: docker/metadata-action@v4.6.0
                with:
                    images: ${{ env.DOCKER_IMAGE }}
            -
                uses: docker/build-push-action@v4
                with:
                    context: .
                    push: ${{ github.event_name != 'pull_request' && github.ref_type == 'tag' }}
                    tags: ${{ steps.meta.outputs.tags }}
                    labels: ${{ steps.meta.outputs.labels }}
