name: Quality Assurance

'on':
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    checks:
        runs-on: ubuntu-latest
        steps:
            -
                uses: actions/checkout@v3.5.2
            -
                uses: ScribeMD/docker-cache@0.3.3
                with:
                    key: ${{ runner.os }}-docker-${{ hashFiles('Makefile', 'Dockerfile') }}
            -
                run: make lint
